#!/bin/bash

if [ $2 ]; then
  port=$2
else
	port=8012
fi
if [ $1 ]; then
  state=$1
else
	state="on"
fi
sock_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/ssh.sock"
if [[ "$state" == "on" ]]
then
  ssh felfel@felfel -MfND $port -S $sock_dir
  echo ssh tunnel started
  sudo networksetup -setsocksfirewallproxy wi-fi localhost $port
  sudo networksetup -setsocksfirewallproxystate wi-fi on
elif [[ "$state" == "off" ]]; then
  #statements
  echo port is in use
  echo try to close
  ssh -S $sock_dir -O exit sajjad.rahnama7@gmail.com
  sudo networksetup -setsocksfirewallproxystate wi-fi off
fi
