# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="sajjad"


# plugins
plugins=(git composer sudo cp z docker mosh osx pip)

# User configuration
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"


# Command aliases
source $HOME/.zsh/aliases.sh

# Environment variable exports
source $HOME/.zsh/exports.sh

# Plugins
source $HOME/.zsh/zsh.plug/docker.zsh
